import * as React from 'react'

/** Tiny stable hash so a stylesheet's tag id reflects its content. */
const hash = (input: string): string => {
  let h = 5381
  for (let i = 0; i < input.length; i++) h = ((h << 5) + h + input.charCodeAt(i)) | 0
  return (h >>> 0).toString(36)
}

/**
 * Client-side ownership of each distinct stylesheet. Several components can render the same CSS
 * (a root plus areas, or two roots); exactly one of them owns the `<style>` tag. Ownership is
 * claimed in insertion order and handed on if the owner unmounts, so the rules never disappear
 * while something still needs them.
 */
const claims = new Map<string, symbol[]>()
const listeners = new Set<() => void>()

const notify = (): void => {
  for (const l of listeners) l()
}

const claim = (id: string, token: symbol): (() => void) => {
  const list = claims.get(id)
  if (list) list.push(token)
  else claims.set(id, [token])
  notify()
  return () => {
    const current = claims.get(id)
    if (!current) return
    const i = current.indexOf(token)
    if (i !== -1) current.splice(i, 1)
    if (current.length === 0) claims.delete(id)
    notify()
  }
}

const isOwner = (id: string, token: symbol): boolean => claims.get(id)?.[0] === token

const subscribe = (listener: () => void): (() => void) => {
  listeners.add(listener)
  return () => listeners.delete(listener)
}

export interface StylesProps {
  css: string
  nonce?: string
}

/**
 * Renders the stylesheet inline as ordinary React output, so it is present in server-rendered
 * HTML, hydrates normally, needs no bundler CSS support, and is removed when the last component
 * using it unmounts.
 *
 * Deliberately not a React 19 hoistable `<style precedence>`: hoisted styles are never removed,
 * so a theme change or a `disabled` toggle would leave stale rules in `<head>`.
 * The CSS is generated by us and contains nothing that needs escaping inside `<style>`.
 */
export function Styles({ css, nonce }: StylesProps): React.JSX.Element | null {
  const id = React.useMemo(() => `glass-scroll-${hash(css)}`, [css])
  const [token] = React.useState(() => Symbol('glass-scroll'))

  React.useEffect(() => claim(id, token), [id, token])

  // Before hydration nobody has claimed anything, so every instance renders the tag and the
  // server HTML matches. The moment effects run, all but the owner drop theirs.
  const owns = React.useSyncExternalStore(
    subscribe,
    () => !claims.has(id) || isOwner(id, token),
    () => true,
  )

  if (!owns) return null
  return (
    <style id={id} nonce={nonce} data-glass-scroll="" dangerouslySetInnerHTML={{ __html: css }} />
  )
}
